[theme]
primaryColor = "#009EDB"
backgroundColor = "#F5F8FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1A1A2E"
font = "sans serif"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false
